import {createUseStyles} from '../Theme';

export default createUseStyles(theme => ({
  'h1-bold': {
    color: theme.text.primary,
    fontFamily: theme.fontFamily.bold,
    fontWeight: '700',
    fontSize: 48,
    lineHeight: 60,
  },
  'h1-medium': {
    color: theme.text.primary,
    fontFamily: theme.fontFamily.medium,
    fontWeight: '500',
    fontSize: 48,
    lineHeight: 60,
  },
  'h1-regular': {
    color: theme.text.primary,
    fontFamily: theme.fontFamily.regular,
    fontWeight: '400',
    fontSize: 48,
    lineHeight: 60,
  },

  'h2-bold': {
    color: theme.text.primary,
    fontFamily: theme.fontFamily.bold,
    fontWeight: '700',
    fontSize: 32,
    lineHeight: 48,
  },
  'h2-medium': {
    color: theme.text.primary,
    fontFamily: theme.fontFamily.medium,
    fontWeight: '500',
    fontSize: 32,
    lineHeight: 48,
  },
  'h2-regular': {
    color: theme.text.primary,
    fontFamily: theme.fontFamily.regular,
    fontWeight: '400',
    fontSize: 32,
    lineHeight: 48,
  },

  'h3-bold': {
    color: theme.text.primary,
    fontFamily: theme.fontFamily.bold,
    fontWeight: '700',
    fontSize: 24,
    lineHeight: 36,
  },
  'h3-medium': {
    color: theme.text.primary,
    fontFamily: theme.fontFamily.medium,
    fontWeight: '500',
    fontSize: 24,
    lineHeight: 36,
  },
  'h3-regular': {
    color: theme.text.primary,
    fontFamily: theme.fontFamily.regular,
    fontWeight: '400',
    fontSize: 24,
    lineHeight: 36,
  },

  'h4-bold': {
    color: theme.text.primary,
    fontFamily: theme.fontFamily.bold,
    fontWeight: '700',
    fontSize: 20,
    lineHeight: 30,
  },
  'h4-medium': {
    color: theme.text.primary,
    fontFamily: theme.fontFamily.medium,
    fontWeight: '500',
    fontSize: 20,
    lineHeight: 30,
  },
  'h4-regular': {
    color: theme.text.primary,
    fontFamily: theme.fontFamily.regular,
    fontWeight: '400',
    fontSize: 20,
    lineHeight: 30,
  },

  'p1-bold': {
    color: theme.text.primary,
    fontFamily: theme.fontFamily.bold,
    fontWeight: '700',
    fontSize: 18,
    lineHeight: 27,
  },
  'p1-medium': {
    color: theme.text.primary,
    fontFamily: theme.fontFamily.medium,
    fontWeight: '500',
    fontSize: 18,
    lineHeight: 27,
  },
  'p1-regular': {
    color: theme.text.primary,
    fontFamily: theme.fontFamily.regular,
    fontWeight: '400',
    fontSize: 18,
    lineHeight: 27,
  },

  'p2-bold': {
    color: theme.text.primary,
    fontFamily: theme.fontFamily.bold,
    fontWeight: '700',
    fontSize: 16,
    lineHeight: 24,
  },
  'p2-medium': {
    color: theme.text.primary,
    fontFamily: theme.fontFamily.medium,
    fontWeight: '500',
    fontSize: 16,
    lineHeight: 24,
  },
  'p2-regular': {
    color: theme.text.primary,
    fontFamily: theme.fontFamily.regular,
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 24,
  },

  'description-bold': {
    color: theme.text.primary,
    fontFamily: theme.fontFamily.bold,
    fontWeight: '700',
    fontSize: 12,
    lineHeight: 18,
  },
  'description-medium': {
    color: theme.text.primary,
    fontFamily: theme.fontFamily.medium,
    fontWeight: '500',
    fontSize: 12,
    lineHeight: 18,
  },
  'caption-regular': {
    color: theme.text.primary,
    fontFamily: theme.fontFamily.regular,
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 18,
  },
  'small-regular': {
    color: theme.text.primary,
    fontFamily: theme.fontFamily.regular,
    fontWeight: '400',
    fontSize: 10,
    lineHeight: 15,
  },

  'label-16-medium': {
    color: theme.text.primary,
    fontFamily: theme.fontFamily.medium,
    fontWeight: '500',
    fontSize: 16,
    lineHeight: 24,
  },
  'label-14-medium': {
    color: theme.text.primary,
    fontFamily: theme.fontFamily.medium,
    fontWeight: '500',
    fontSize: 14,
    lineHeight: 17,
  },
  'label-10-medium': {
    color: theme.text.primary,
    fontFamily: theme.fontFamily.medium,
    fontWeight: '500',
    fontSize: 10,
    lineHeight: 15,
  },
  'label-14-regular': {
    color: theme.text.primary,
    fontFamily: theme.fontFamily.regular,
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 17,
  },
  'label-14-bold': {
    color: theme.text.primary,
    fontFamily: theme.fontFamily.bold,
    fontWeight: '700',
    fontSize: 14,
    lineHeight: 17,
  },
}));
